%YAML:1.0

# settings
calibrate_imu: 0  # 0: no imu calibration and use default values. 1: calibrate imu
show_configuration: 0
average_nums: 100
imu_lidar_extrinsic_angle: 0.0
imu_misalign_angle: 0.0
line_num: 16 
scan_num: 2000
scan_period: 0.1
edge_threshold: 0.5
surf_threshold: 0.5
nearest_feature_search_sq_dist: 25
verbose: 0
icp_freq: 5
max_lidar_nums: 200000
num_iter: 30
lidar_scale: 1
lidar_std: 0.01

# topic names
imu_topic: "/imu0"
lidar_topic: "/rslidar_points"
lidar_odometry_topic: "/laser_odom_to_init"
lidar_mapping_topic: "/integrated_to_init"

# noice parameters
acc_n: 70000
gyr_n: 0.02
acc_w: 500
gyr_w: 0.00005

init_pos_std: !!opencv-matrix
   rows: 3
   cols: 1
   dt: d
   data: [0.0, 0.0, 0.0]
   
init_vel_std: !!opencv-matrix
   rows: 3
   cols: 1
   dt: d
   data: [0.0, 0.0, 0.0]

init_att_std: !!opencv-matrix
   rows: 3
   cols: 1
   dt: d
   data: [0.0, 0.0, 0.0]
   
init_acc_std: !!opencv-matrix
   rows: 3
   cols: 1
   dt: d
   data: [0.01, 0.01, 0.02]
      
init_gyr_std: !!opencv-matrix
   rows: 3
   cols: 1
   dt: d
   data: [0.002, 0.002, 0.002]
  
# initial IMU biases
init_ba: !!opencv-matrix
   rows: 3
   cols: 1
   dt: d
   data: [0.0,0.0,0.0]
   
init_bw: !!opencv-matrix
   rows: 3
   cols: 1
   dt: d
   data: [0.0,0.0,0.0]
   
# extrinsic parameters
init_ti2l: !!opencv-matrix
   rows: 3
   cols: 1
   dt: d
   data: [-0.003350330582203402, 0.0334020595702096, 0.0382448998361715]
   
init_ri2l: !!opencv-matrix
   rows: 3
   cols: 3
   dt: d
   data:  [ 0.0114318398343499, 0.012846239026906, -0.9998600715418787, 
           -0.9999218409705174, 0.007135352162451601, -0.0113390788033412, 
            0.006988718210393499, 0.9998960369567579, 0.0129260498927925]
   # data:  [ 0.000001, 0.087149, -0.996195,
   #         -1.000000, 0.000115, -0.000115,
   #          0.000001, 0.996195, 0.087149]

